name: Backend CI

on:
  pull_request:
    paths:
      - "backend/**"
    branches:
      - "main"

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: ["temurin"]
        java-version: ["25"]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Java version
        env:
          CI_JAVA_VERSION: ${{ matrix.java-version }}
        run: echo $CI_JAVA_VERSION
      - name: Set up JDK ${{ matrix.distribution }} ${{ matrix.java-version }}
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Check
        run: ./gradlew check
